# Generated by Django 5.1.4 on 2025-02-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('I_diff', models.DecimalField(decimal_places=1, max_digits=3)),
                ('II_diff', models.DecimalField(decimal_places=1, max_digits=3)),
                ('III_diff', models.DecimalField(decimal_places=1, max_digits=3)),
                ('IV_diff', models.DecimalField(decimal_places=1, max_digits=3)),
                ('IV_a_diff', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
        ),
    ]
