# Generated by Django 5.1.4 on 2025-02-13 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('I_score', models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(1010000)])),
                ('II_score', models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(1010000)])),
                ('III_score', models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(1010000)])),
                ('IV_score', models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(1010000)])),
                ('IV_a_score', models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(1010000)])),
                ('I_clear', models.BooleanField(default=False)),
                ('II_clear', models.BooleanField(default=False)),
                ('III_clear', models.BooleanField(default=False)),
                ('IV_clear', models.BooleanField(default=False)),
                ('IV_a_clear', models.BooleanField(default=False)),
                ('I_fc', models.BooleanField(default=False)),
                ('II_fc', models.BooleanField(default=False)),
                ('III_fc', models.BooleanField(default=False)),
                ('IV_fc', models.BooleanField(default=False)),
                ('IV_a_fc', models.BooleanField(default=False)),
                ('I_ap', models.BooleanField(default=False)),
                ('II_ap', models.BooleanField(default=False)),
                ('III_ap', models.BooleanField(default=False)),
                ('IV_ap', models.BooleanField(default=False)),
                ('IV_a_ap', models.BooleanField(default=False)),
            ],
        ),
    ]
