# Generated by Django 5.1.4 on 2025-02-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_score_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='user',
        ),
    ]
